### ISSUE TITLE
Empty repositories

### ISSUE THREAD

**Issue by Eskander88** [mheinzler/OpenContextPath#1]
I came by link from `packagecontrol.io` . But repositories doesn't exist.

**Comment by mheinzler** [comment]
Can you explain what exactly the issue is you see? Package Control seems fine to me.

**Comment by Eskander88** [comment]
I'm sorry, apparently there are some problems with my sublime build. I couldn't install the package. After reinstalling it works.

**Comment by mheinzler** [comment]
No worries. Happy that it works now.
