### ISSUE TITLE
recognize linux user home directory

### ISSUE THREAD

**Issue by arcturus140** [mheinzler/OpenContextPath#2]
in Linux, paths relative to the current user directory start with `~`. It represents the home root directory, aka $HOME. The linux environment translates these paths for the current user. 

for example, `~/.bashrc` translates to the user joe as `/home/joe/.bashrc`. This format is very common on Linux, it would be very helpful if OpenContextPath can recognize this pattern as a path.

**Comment by mheinzler** [comment]
Missed those as I'm mostly working on Windows. I thought Python would handle these paths automatically but apparently it doesn't. An update will be available soon.
